# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\user\Documents\qt\new\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os
import group_popup
import schedule_popup
import people_popup
import shutil


class Ui_main(object):
    def setupUi(self, main):
        main.setObjectName("main")
        main.setFixedSize(400, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(main.sizePolicy().hasHeightForWidth())
        main.setSizePolicy(sizePolicy)
        main.setStyleSheet("background-color:rgb(255,255,255);")
        self.centralwidget = QtWidgets.QWidget(main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setStyleSheet("QTabBar::tab { height: 30px; width: 120px; }")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideMiddle)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.people_num_layout = QtWidgets.QHBoxLayout()
        self.people_num_layout.setObjectName("people_num_layout")
        self.people_num = QtWidgets.QLabel(self.tab_1)
        self.people_num.setStyleSheet("font: 75 16pt \"맑은 고딕\";")
        self.people_num.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.people_num.setTextFormat(QtCore.Qt.AutoText)
        self.people_num.setObjectName("people_num")
        self.people_num_layout.addWidget(self.people_num)
        self.verticalLayout_2.addLayout(self.people_num_layout)
        self.scrollArea = QtWidgets.QScrollArea(self.tab_1)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.people_scroll_area = QtWidgets.QWidget()
        self.people_scroll_area.setGeometry(QtCore.QRect(0, 0, 448, 373))
        self.people_scroll_area.setObjectName("people_scroll_area")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.people_scroll_area)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.people_list = QtWidgets.QListWidget(self.people_scroll_area)
        self.people_list.setObjectName("people_list")
        self.horizontalLayout.addWidget(self.people_list)
        self.scrollArea.setWidget(self.people_scroll_area)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(0, -1, -1, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.people_make_button = QtWidgets.QPushButton(self.tab_1)
        self.people_make_button.clicked.connect(self.people_make_button_clicked)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.people_make_button.sizePolicy().hasHeightForWidth())
        self.people_make_button.setSizePolicy(sizePolicy)
        self.people_make_button.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.people_make_button.setFont(font)
        self.people_make_button.setStyleSheet("")
        self.people_make_button.setIconSize(QtCore.QSize(10, 10))
        self.people_make_button.setObjectName("people_make_button")
        self.horizontalLayout_2.addWidget(self.people_make_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.people_num_layout_2 = QtWidgets.QHBoxLayout()
        self.people_num_layout_2.setObjectName("people_num_layout_2")
        self.group_num = QtWidgets.QLabel(self.tab_2)
        self.group_num.setStyleSheet("font: 75 16pt \"맑은 고딕\";")
        self.group_num.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.group_num.setTextFormat(QtCore.Qt.AutoText)
        self.group_num.setObjectName("group_num")
        self.people_num_layout_2.addWidget(self.group_num)
        self.verticalLayout_5.addLayout(self.people_num_layout_2)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.tab_2)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.tea_scroll_area = QtWidgets.QWidget()
        self.tea_scroll_area.setGeometry(QtCore.QRect(0, 0, 448, 421))
        self.tea_scroll_area.setObjectName("tea_scroll_area")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tea_scroll_area)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.group_list = QtWidgets.QListWidget(self.tea_scroll_area)
        self.group_list.setObjectName("group_list")
        self.horizontalLayout_4.addWidget(self.group_list)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(4, 4, 4, 4)
        self.horizontalLayout_3.setSpacing(4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.group_make_button = QtWidgets.QPushButton(self.tea_scroll_area)
        self.group_make_button.setObjectName("group_make_button")
        self.group_make_button.clicked.connect(self.group_make_button_clicked)
        self.horizontalLayout_3.addWidget(self.group_make_button)
        self.group_delete_button = QtWidgets.QPushButton(self.tea_scroll_area)
        self.group_delete_button.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.group_delete_button.sizePolicy().hasHeightForWidth())
        self.group_delete_button.setSizePolicy(sizePolicy)
        self.group_delete_button.setObjectName("group_delete_button")
        self.group_delete_button.clicked.connect(self.group_delete_button_clicked)
        self.horizontalLayout_3.addWidget(self.group_delete_button)
        self.schedule_make_button = QtWidgets.QPushButton(self.tea_scroll_area)
        self.schedule_make_button.clicked.connect(self.schedule_make_button_clicked)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.schedule_make_button.sizePolicy().hasHeightForWidth())
        self.schedule_make_button.setSizePolicy(sizePolicy)
        self.schedule_make_button.setObjectName("schedule_make_button")
        self.horizontalLayout_3.addWidget(self.schedule_make_button)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout_6.addLayout(self.verticalLayout_4)
        self.scrollArea_2.setWidget(self.tea_scroll_area)
        self.verticalLayout_5.addWidget(self.scrollArea_2)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        main.setCentralWidget(self.centralwidget)

        self.retranslateUi(main)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(main)
        
    def group_num_search(self):
        path = '../data/' 
        file_list = os.listdir(path)
        return len(file_list)
    
    def people_num_search(self):
        path = '../data/'
        group_list = os.listdir(path)
        people_num=0
        for i in group_list :
            people_num +=len(os.listdir(path+i))
        return people_num

    def retranslateUi(self, main):
        people_numbers = self.people_num_search()
        group_numbers = self.group_num_search()
        _translate = QtCore.QCoreApplication.translate
        main.setWindowTitle(_translate("main", "CampuScheduler"))
        self.people_num.setText(_translate("main", "People 👤 "+str(people_numbers)))
        self.people_list_refresh()
        self.people_make_button.setText(_translate("main", "+"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("main", "PEOPLE"))
        self.group_num.setText(_translate("main", "Group 👥 "+str(group_numbers)))
        self.group_list_refresh()
        self.group_make_button.setText(_translate("main", "그룹 생성"))
        self.group_delete_button.setText(_translate("main", "그룹 삭제"))
        self.schedule_make_button.setText(_translate("main", "스케쥴 생성"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("main", "GROUP"))
        
    def people_list_refresh(self):
        people_numbers = self.people_num_search()
        self.people_num.setText("People 👤 "+str(people_numbers))
        self.people_list.clear()
        path = '../data/'
        group_list = os.listdir(path)
        for i in group_list :
            people_list = os.listdir(path+i)
            for j in people_list :
                student_name = j.rstrip('.json')
                temp_item = QtWidgets.QListWidgetItem(student_name+'_'+i)
                self.people_list.addItem(temp_item)
    
    def group_list_refresh(self):
        group_numbers = self.group_num_search()
        self.group_num.setText("Group 👥 "+str(group_numbers))
        self.group_list.clear()
        path = '../data/'
        group_list = os.listdir(path)
        for i in group_list :
            temp_item = QtWidgets.QListWidgetItem(i)
            self.group_list.addItem(temp_item)
    
    def group_make_button_clicked(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = group_popup.Ui_MainWindow()
        self.ui.setupUi(self.window,self)
        self.window.show()
              
    def group_delete_button_clicked(self):
        group_selected_row = self.group_list.currentRow()
        group_selected_item = self.group_list.currentItem()
        if group_selected_item == None:
            QtWidgets.QMessageBox.warning(QtWidgets.QMainWindow(),'CampuScheduler','그룹을 선택하세요.')
            return 0
        path = '../data/'+group_selected_item.text()
        shutil.rmtree(path)
        self.group_list.takeItem(group_selected_row)
        self.group_list_refresh()
        
    def schedule_make_button_clicked(self):
        group_selected_item = self.group_list.currentItem()
        if group_selected_item == None:
            QtWidgets.QMessageBox.warning(QtWidgets.QMainWindow(),'CampuScheduler','그룹을 선택하세요.')
            return 0
        self.window = QtWidgets.QMainWindow()
        self.ui = schedule_popup.Ui_MainWindow()
        self.ui.setupUi(self.window,self,group_selected_item.text())
        self.window.show()
        
    def people_make_button_clicked(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = people_popup.Ui_MainWindow()
        self.ui.setupUi(self.window,self)
        self.window.show()
        

if __name__ == "__main__":
    import sys
    if not os.path.exists('../data/'):
        os.makedirs('../data/')
    app = QtWidgets.QApplication(sys.argv)
    main = QtWidgets.QMainWindow()
    ui = Ui_main()
    ui.setupUi(main)
    main.show()
    sys.exit(app.exec_())
