# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\user\Documents\qt\new\people_popup.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os
import Imageprocessing

class Ui_MainWindow(object):
    def setupUi(self, MainWindow,parent):
        self.myMainWindow = MainWindow
        self.parent = parent
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(400, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(4, 4, 4, 4)
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.file_directory = QtWidgets.QLineEdit(self.centralwidget)
        self.file_directory.setReadOnly(True)
        self.file_directory.setObjectName("file_directory")
        self.horizontalLayout.addWidget(self.file_directory)
        self.people_pop_up_search_button = QtWidgets.QPushButton(self.centralwidget)
        self.people_pop_up_search_button.clicked.connect(self.people_pop_up_search_button_clicked)
        self.people_pop_up_search_button.setObjectName("people_pop_up_search_button")
        self.horizontalLayout.addWidget(self.people_pop_up_search_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(4, 4, 4, 4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.student_name = QtWidgets.QLineEdit(self.centralwidget)
        self.student_name.setObjectName("student_name")
        self.horizontalLayout_2.addWidget(self.student_name)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(4, 4, 4, 4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.student_id = QtWidgets.QLineEdit(self.centralwidget)
        self.student_id.setObjectName("student_id")
        self.horizontalLayout_3.addWidget(self.student_id)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(4, 4, 4, 4)
        self.horizontalLayout_5.setSpacing(4)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.group_list = QtWidgets.QListWidget(self.groupBox)
        self.group_list.setObjectName("group_list")
        self.verticalLayout_3.addWidget(self.group_list)
        self.horizontalLayout_5.addWidget(self.groupBox)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(4, 4, 4, 4)
        self.horizontalLayout_4.setSpacing(4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.people_popup_accept_button = QtWidgets.QPushButton(self.centralwidget)
        self.people_popup_accept_button.clicked.connect(self.people_popup_accept_button_clicked)
        self.people_popup_accept_button.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.people_popup_accept_button.sizePolicy().hasHeightForWidth())
        self.people_popup_accept_button.setSizePolicy(sizePolicy)
        self.people_popup_accept_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.people_popup_accept_button.setObjectName("people_popup_accept_button")
        self.horizontalLayout_4.addWidget(self.people_popup_accept_button)
        self.people_popup_cancel_button = QtWidgets.QPushButton(self.centralwidget)
        self.people_popup_cancel_button.clicked.connect(self.people_popup_cancel_button_clicked)
        self.people_popup_cancel_button.setObjectName("people_popup_cancel_button")
        self.horizontalLayout_4.addWidget(self.people_popup_cancel_button)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.group_list_refresh()
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CampuScheduler"))
        self.label_3.setText(_translate("MainWindow", "파일 : "))
        self.people_pop_up_search_button.setText(_translate("MainWindow", "찾아보기..."))
        self.label_2.setText(_translate("MainWindow", "이름 : "))
        self.label.setText(_translate("MainWindow", "학번 : "))
        self.groupBox.setTitle(_translate("MainWindow", "그룹"))
        self.people_popup_accept_button.setText(_translate("MainWindow", "확인"))
        self.people_popup_cancel_button.setText(_translate("MainWindow", "취소"))
        
    def group_list_refresh(self):
        self.group_list.clear()
        path = '../data/'
        group_list = os.listdir(path)
        for i in group_list :
            temp_item = QtWidgets.QListWidgetItem(i)
            self.group_list.addItem(temp_item)
        
    def people_pop_up_search_button_clicked(self):
        path = QtWidgets.QFileDialog.getOpenFileName(self.myMainWindow, 'Open File')
        self.file_directory.setText(str(path[0]))
       
    def people_popup_accept_button_clicked(self):
        if len(self.student_name.text())<1 :
            QtWidgets.QMessageBox.warning(QtWidgets.QMainWindow(),'CampuScheduler','이름을 입력하세요.')
            return 0
        if len(self.student_id.text())<1 :
            QtWidgets.QMessageBox.warning(QtWidgets.QMainWindow(),'CampuScheduler','학번을 입력하세요.')
            return 0
        if len(self.file_directory.text())<1 :
            QtWidgets.QMessageBox.warning(QtWidgets.QMainWindow(),'CampuScheduler','파일을 입력하세요.')
            return 0
        if self.group_list.currentItem() == None:
            QtWidgets.QMessageBox.warning(QtWidgets.QMainWindow(),'CampuScheduler','그룹을 선택하세요.')
            return 0
        
        input_list = []
        input_list.append(self.student_name.text())
        input_list.append(self.student_id.text())
        input_list.append(self.file_directory.text())
        input_list.append(str(self.group_list.currentItem().text()))
        try:
            Imageprocessing.run(input_list)
        except Exception as e:
            QtWidgets.QMessageBox.warning(QtWidgets.QMainWindow(),'CampuScheduler',str(e))
            self.myMainWindow.close()
            
        self.parent.people_list_refresh()
        self.myMainWindow.close()
           
    def people_popup_cancel_button_clicked(self):
        self.parent.people_list_refresh()
        self.myMainWindow.close()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
