# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\user\Documents\qt\new\schedule_popup.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import Scheduling

class Ui_MainWindow(object):
    def setupUi(self, MainWindow,parent,path):
        self.myMainWindow = MainWindow
        self.parent = parent
        self.path = path
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(640, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(4, 4, 4, 4)
        self.horizontalLayout_8.setSpacing(4)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.schedule_popup_all_possible_flag = QtWidgets.QRadioButton(self.centralwidget)
        self.schedule_popup_all_possible_flag.setObjectName("schedule_popup_all_possible_flag")
        self.horizontalLayout_8.addWidget(self.schedule_popup_all_possible_flag)
        self.schedule_popup_equality_flag = QtWidgets.QRadioButton(self.centralwidget)
        self.schedule_popup_equality_flag.setObjectName("schedule_popup_equality_flag")
        self.horizontalLayout_8.addWidget(self.schedule_popup_equality_flag)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(4, 4, 4, 4)
        self.horizontalLayout_7.setSpacing(4)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.schedule_popup_duplication_flag = QtWidgets.QCheckBox(self.centralwidget)
        self.schedule_popup_duplication_flag.setObjectName("schedule_popup_duplication_flag")
        self.horizontalLayout_7.addWidget(self.schedule_popup_duplication_flag)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(4, 4, 4, 4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.schedule_popup_time_length = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.schedule_popup_time_length.sizePolicy().hasHeightForWidth())
        self.schedule_popup_time_length.setSizePolicy(sizePolicy)
        self.schedule_popup_time_length.setMaximumSize(QtCore.QSize(40, 25))
        self.schedule_popup_time_length.setObjectName("schedule_popup_time_length")
        self.horizontalLayout_2.addWidget(self.schedule_popup_time_length)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(4, 4, 4, 4)
        self.horizontalLayout_5.setSpacing(4)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.schedule_popup_people_max = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.schedule_popup_people_max.sizePolicy().hasHeightForWidth())
        self.schedule_popup_people_max.setSizePolicy(sizePolicy)
        self.schedule_popup_people_max.setMaximumSize(QtCore.QSize(40, 25))
        self.schedule_popup_people_max.setObjectName("schedule_popup_people_max")
        self.horizontalLayout_5.addWidget(self.schedule_popup_people_max)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(4, 4, 4, 4)
        self.horizontalLayout_6.setSpacing(4)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.schedule_popup_people_min = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.schedule_popup_people_min.sizePolicy().hasHeightForWidth())
        self.schedule_popup_people_min.setSizePolicy(sizePolicy)
        self.schedule_popup_people_min.setMaximumSize(QtCore.QSize(40, 25))
        self.schedule_popup_people_min.setObjectName("schedule_popup_people_min")
        self.horizontalLayout_6.addWidget(self.schedule_popup_people_min)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.schedule_list = QtWidgets.QListWidget(self.groupBox)
        self.schedule_list.setObjectName("schedule_list")
        self.horizontalLayout_9.addWidget(self.schedule_list)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_3.setSpacing(4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(4, 4, 4, 4)
        self.horizontalLayout_11.setSpacing(4)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_11.addWidget(self.label_9)
        self.schedule_popup_input_starttime = QtWidgets.QDateTimeEdit(self.groupBox)
        self.schedule_popup_input_starttime.setTime(QtCore.QTime.fromString("12:00", "hh:mm"))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.schedule_popup_input_starttime.sizePolicy().hasHeightForWidth())
        self.schedule_popup_input_starttime.setSizePolicy(sizePolicy)
        self.schedule_popup_input_starttime.setMinimumSize(QtCore.QSize(150, 0))
        self.schedule_popup_input_starttime.setDate(QtCore.QDate(2000, 1, 3))
        self.schedule_popup_input_starttime.setObjectName("schedule_popup_input_starttime")
        self.horizontalLayout_11.addWidget(self.schedule_popup_input_starttime)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setContentsMargins(4, 4, 4, 4)
        self.horizontalLayout_12.setSpacing(4)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_12.addWidget(self.label_10)
        self.schedule_popup_input_endtime = QtWidgets.QDateTimeEdit(self.groupBox)
        self.schedule_popup_input_endtime.setTime(QtCore.QTime.fromString("12:00", "hh:mm"))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.schedule_popup_input_endtime.sizePolicy().hasHeightForWidth())
        self.schedule_popup_input_endtime.setSizePolicy(sizePolicy)
        self.schedule_popup_input_endtime.setMinimumSize(QtCore.QSize(150, 0))
        self.schedule_popup_input_endtime.setDate(QtCore.QDate(2000, 1, 3))
        self.schedule_popup_input_endtime.setObjectName("schedule_popup_input_endtime")
        self.horizontalLayout_12.addWidget(self.schedule_popup_input_endtime)
        self.verticalLayout_3.addLayout(self.horizontalLayout_12)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem5)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.schedule_popup_input_button = QtWidgets.QPushButton(self.groupBox)
        self.schedule_popup_input_button.clicked.connect(self.schedule_popup_input_button_clicked)
        self.schedule_popup_input_button.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.schedule_popup_input_button.sizePolicy().hasHeightForWidth())
        self.schedule_popup_input_button.setSizePolicy(sizePolicy)
        self.schedule_popup_input_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.schedule_popup_input_button.setObjectName("schedule_popup_input_button")
        self.horizontalLayout_10.addWidget(self.schedule_popup_input_button)
        self.schedule_popup_delete_button = QtWidgets.QPushButton(self.groupBox)
        self.schedule_popup_delete_button.clicked.connect(self.schedule_popup_delete_button_clicked)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.schedule_popup_delete_button.sizePolicy().hasHeightForWidth())
        self.schedule_popup_delete_button.setSizePolicy(sizePolicy)
        self.schedule_popup_delete_button.setObjectName("schedule_popup_delete_button")
        self.horizontalLayout_10.addWidget(self.schedule_popup_delete_button)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_9.addLayout(self.verticalLayout_3)
        self.horizontalLayout.addWidget(self.groupBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(4, 4, 4, 4)
        self.horizontalLayout_4.setSpacing(4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.schedule_popup_accept_button = QtWidgets.QPushButton(self.centralwidget)
        self.schedule_popup_accept_button.clicked.connect(self.schedule_popup_accept_button_clicked)
        self.schedule_popup_accept_button.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.schedule_popup_accept_button.sizePolicy().hasHeightForWidth())
        self.schedule_popup_accept_button.setSizePolicy(sizePolicy)
        self.schedule_popup_accept_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.schedule_popup_accept_button.setObjectName("schedule_popup_accept_button")
        self.horizontalLayout_4.addWidget(self.schedule_popup_accept_button)
        self.schedule_popup_cancel_button = QtWidgets.QPushButton(self.centralwidget)
        self.schedule_popup_cancel_button.clicked.connect(self.schedule_popup_cancel_button_clicked)
        self.schedule_popup_cancel_button.setObjectName("schedule_popup_cancel_button")
        self.horizontalLayout_4.addWidget(self.schedule_popup_cancel_button)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CampuScheduler"))
        self.schedule_popup_all_possible_flag.setText(_translate("MainWindow", "모두 되는 시간 찾기"))
        self.schedule_popup_equality_flag.setText(_translate("MainWindow", "균등 분배"))
        self.schedule_popup_duplication_flag.setText(_translate("MainWindow", "중복 허용"))
        self.label_2.setText(_translate("MainWindow", "시간대의 길이 : "))
        self.label_3.setText(_translate("MainWindow", "분"))
        self.label_6.setText(_translate("MainWindow", "시간대별 최대 인원 : "))
        self.label_5.setText(_translate("MainWindow", "명"))
        self.label_7.setText(_translate("MainWindow", "시간대별 최소 인원 : "))
        self.label_8.setText(_translate("MainWindow", "명"))
        self.groupBox.setTitle(_translate("MainWindow", "일정"))
        self.label_9.setText(_translate("MainWindow", "시작 :"))
        self.schedule_popup_input_starttime.setDisplayFormat(_translate("MainWindow", "dddd AP h:mm"))
        self.label_10.setText(_translate("MainWindow", "종료 : "))
        self.schedule_popup_input_endtime.setDisplayFormat(_translate("MainWindow", "dddd AP h:mm"))
        self.schedule_popup_input_button.setText(_translate("MainWindow", "입력"))
        self.schedule_popup_delete_button.setText(_translate("MainWindow", "삭제"))
        self.schedule_popup_accept_button.setText(_translate("MainWindow", "확인"))
        self.schedule_popup_cancel_button.setText(_translate("MainWindow", "취소"))

    def schedule_popup_cancel_button_clicked(self):
            self.parent.group_list_refresh()
            self.myMainWindow.close()
            
    def schedule_popup_accept_button_clicked(self):
        ########입력인자##########
        time_length = 0 #시간대 길이
        time_number = 0 #시간대 개수
        duplication_flag = False    #중복 허용
        all_possible_flag = False   #모두 되는 시간 찾기
        equality_flag = False   #균등 분배
        people_min = None  #최소 사람수
        people_max = None  #최대 사람수
        groupname = self.path  #그룹 이름
        ##########################
        schedule_input_string = ''
        
        schedule_input_string+='-g '+self.path+' '
        
        if self.schedule_popup_all_possible_flag.isChecked():
            schedule_input_string+='-a '
        elif self.schedule_popup_equality_flag.isChecked():
            schedule_input_string+='-e '
        else:
            QtWidgets.QMessageBox.warning(QtWidgets.QMainWindow(),'CampuScheduler','라디오박스를 적어도 하나 선택하세요.')
            return 0
        
        if self.schedule_popup_duplication_flag.isChecked():
            schedule_input_string+='-r '
        
        if not self.schedule_popup_time_length.text():
            QtWidgets.QMessageBox.warning(QtWidgets.QMainWindow(),'CampuScheduler','시간대의 길이를 입력하세요.')
            return 0
        else:
            schedule_input_string+='-l '+self.schedule_popup_time_length.text()+' '
        
        if not self.schedule_popup_people_max.text():
            QtWidgets.QMessageBox.warning(QtWidgets.QMainWindow(),'CampuScheduler','시간대별 최대인원을 입력하세요.')
            return 0
        else:
            schedule_input_string+='-P '+self.schedule_popup_people_max.text()+' '
            
        if not self.schedule_popup_people_min.text():
            QtWidgets.QMessageBox.warning(QtWidgets.QMainWindow(),'CampuScheduler','시간대별 최소인원을 입력하세요.')
            return 0
        else:
            schedule_input_string+='-p '+self.schedule_popup_people_min.text()+' '
        
        schedule_input_string+='-n '+str(self.schedule_list.count())+' '
        
        for i in range (self.schedule_list.count()) :
            split_string_list = self.schedule_list.item(i).text().split()
            if split_string_list[0] == '월':
                schedule_input_string+='0 '
            elif split_string_list[0] == '화':
                schedule_input_string+='1 '
            elif split_string_list[0] == '수':
                schedule_input_string+='2 '
            elif split_string_list[0] == '목':
                schedule_input_string+='3 '
            elif split_string_list[0] == '금':
                schedule_input_string+='4 '
            elif split_string_list[0] == '토':
                schedule_input_string+='5 '
            elif split_string_list[0] == '일':
                schedule_input_string+='6 '
            
            num=float(split_string_list[1].split(':')[0])
            if (split_string_list[1].split(':')[1] == '30'):
                num+=0.5
                
            schedule_input_string+=str(num)+' '
            
            num=float(split_string_list[4].split(':')[0])
            if (split_string_list[4].split(':')[1] == '30'):
                num+=0.5
                
            schedule_input_string+=str(num)+' '
        schedule_input_string = schedule_input_string.rstrip()
        print(schedule_input_string)
        schedule_input_string_list = schedule_input_string.split(' ')
        print(schedule_input_string_list)
        result = 0
        try:
            result = Scheduling.run(schedule_input_string_list)
        except Exception as e:
            QtWidgets.QMessageBox.warning(QtWidgets.QMainWindow(),'CampuScheduler',str(e))
            self.myMainWindow.close()

        if result == 0:
            QtWidgets.QMessageBox.warning(QtWidgets.QMainWindow(),'CampuScheduler','가능한 스케쥴이 없습니다.')
            self.myMainWindow.close()
        else:
            QtWidgets.QMessageBox.warning(QtWidgets.QMainWindow(),'CampuScheduler','스케쥴 생성이 완료되었습니다.')
            self.myMainWindow.close()
    
        self.parent.group_list_refresh()
        self.myMainWindow.close()

    def schedule_popup_input_button_clicked(self):
        schedule_input=self.schedule_popup_input_starttime.dateTime().toString('ddd hh:mm')+' - '+self.schedule_popup_input_endtime.dateTime().toString('ddd hh:mm')
        self.schedule_list.addItem(schedule_input)
        
    def schedule_popup_delete_button_clicked(self):
        selected_row = self.schedule_list.currentRow()
        self.schedule_list.takeItem(selected_row)
        
        
